trigger:
- main
- feature/*

schedules:
  - cron: "35 17 * * *"
    displayName: 'Scheduled by YAML'
    branches:
      include:
        - main
    always: true

jobs:
  - job: build
    displayName: 'build'
    pool:
     vmImage: 'ubuntu-latest'
    steps:
      - bash: echo "build application"

  - job: unittest
    displayName: 'unit-test'
    pool:
     vmImage: 'ubuntu-latest'
    steps:
      - bash: echo "running unittests"
