trigger:
- main
- feature/*

schedules:
  - cron: "35 17 * *"
    displayName: 'Agendamento pelo YAML'
    branches:
      include:
        - main
    always: true

pool:
  vmImage: 'ubuntu-latest'

steps:
  - script: echo Primeiro pipeline com YAML
    displayName: 'Script no YAML'
  - script: |
      echo Add other task to build, test, and deploy your project.
      echo See https://aka.ms/yaml
    displayName: 'Run a multi-line script'
