pool:
 vmImage: 'ubuntu-latest'

steps:
  - script: echo "Usando tasks"
    displayName: "Rodar script"
  - task: PowerShell@2
    inputs:
      targetType: 'inline'
      script: |
        # Write your PowerShell commands here.
        Write-Host "Usando Tasks no YAML"
        Write-Host $(variable-test)
        Write-Host $(variable-secret)
  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '.'
      ArtifactName: 'drop-yaml'
      publishLocation: 'Container'